# Generated by Django 3.0.5 on 2021-02-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='slider',
            name='image2',
            field=models.ImageField(blank=True, upload_to='home/images'),
        ),
    ]
